<a href="https://colab.research.google.com/github/itrail/AMW_ML_Laboratorium/blob/main/numpy/Array_vs_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
L = [1,2,3]

In [11]:
A = np.array([1,2,3])

In [12]:
for elem in L:
  print(elem)

1
2
3


In [13]:
for elem in A:
  print(elem)

1
2
3


In [14]:
L.append(4)
L

[1, 2, 3, 4]

In [15]:
A.append(4) #nie zadziala

AttributeError: ignored

In [16]:
L + [5]

[1, 2, 3, 4, 5]

In [17]:
A + np.array([4]) #zwiększenie wartości elementów o 4

array([5, 6, 7])

In [18]:
A + np.array([4,5,6]) #zwiększenie wartości kolejnych elementów o 4,5 i 6

array([5, 7, 9])

In [19]:
2 * A #dwukrotne zwiększenie wartości elementów w arayu

array([2, 4, 6])

In [20]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [21]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [23]:
L2 = []
for elem in L:
  L2.append(elem + 3)
L2

[4, 5, 6, 7]

In [26]:
L2 = [elem + 3 for elem in L]
L2

[4, 5, 6, 7]

In [29]:
L2 = []
for elem in L:
  L2.append(elem**2)
L2

[1, 4, 9, 16]

In [30]:
A**2

array([1, 4, 9])

In [31]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [32]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [33]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [34]:
np.sqrt(L)

array([1.        , 1.41421356, 1.73205081, 2.        ])