<a href="https://colab.research.google.com/github/itrail/AMW_ML_Laboratorium/blob/main/numpy/Macierze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [2]:
L[0]

[1, 2]

In [3]:
L[1][1]

4

In [5]:
import numpy as np

A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
A[0]

array([1, 2])

In [7]:
A[1][1]

4

In [8]:
A[1,1]

4

In [9]:
A[:,0]

array([1, 3])

In [14]:
A[:,1]

array([2, 4])

In [15]:
A[1:]

array([[3, 4]])

In [16]:
A.T

array([[1, 3],
       [2, 4]])

In [17]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#iloczyn skalarny macierzy

A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [21]:
#wyznacznik macierzy

np.linalg.det(A)

-2.0000000000000004

In [20]:
#obliczenie odwróconej macierzy

np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [24]:
#przekątna

np.diag(A)

array([1, 4])

In [25]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [26]:
#zsumowanie elementów przekatnej

np.trace(A)

5

In [28]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [29]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
10 * np.ones((3,2))

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3, dtype=int, k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [37]:
np.random.random((2, 3))

array([[0.21039355, 0.95055906, 0.91621176],
       [0.44899163, 0.83961759, 0.72484203]])

In [38]:
np.random.randn(2, 3)

array([[-0.35851802, -0.21146426, -0.09747201],
       [ 0.63059861, -0.09143604, -0.24601178]])

In [39]:
R = np.random.randn(10000)

In [40]:
R.mean()

-0.013908837484336797

In [41]:
np.mean(R)

-0.013908837484336797

In [42]:
#wariancja

R.var()

1.0082820376617656

In [43]:
R = np.random.randn(10000, 3)

In [44]:
R.mean(axis=0)

array([-0.0008891 , -0.01254151, -0.0007535 ])

In [45]:
R.mean(axis=0).shape

(3,)

In [46]:
np.cov(R).shape

(10000, 10000)

In [47]:
np.cov(R.T)

array([[ 1.01045322, -0.00465171,  0.01599549],
       [-0.00465171,  0.98700298,  0.01389984],
       [ 0.01599549,  0.01389984,  0.99949506]])

In [48]:
np.cov(R, rowvar=False)

array([[ 1.01045322, -0.00465171,  0.01599549],
       [-0.00465171,  0.98700298,  0.01389984],
       [ 0.01599549,  0.01389984,  0.99949506]])

In [49]:
np.random.randint(0, 10, size=(3, 3))

array([[1, 1, 6],
       [5, 5, 6],
       [6, 8, 4]])

In [51]:
np.random.choice(10, size=(3, 3))

array([[4, 1, 1],
       [3, 5, 1],
       [2, 2, 9]])